/* Generated By:JavaCC: Do not edit this line. Form2TreeConstants.java */
package com.example.ooabe.parsers.f2t;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Form2TreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP = 3;
  /** RegularExpression Id. */
  int TERM = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int LD = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<OP>",
    "<TERM>",
    "<LETTER>",
    "<LD>",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
